ALTER TABLE `D_AC` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `D_BrandNames` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `D_Formulary` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `D_Formulations` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `D_ROA` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `Diagnoses` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `MedPlan` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `MedPlan_NoteTypes` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `MedPlan_notes` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `Patient_Exit` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `Patient_Exit_Orders` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `Patient_exit_reasons` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `Patient_trans` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `People` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `People_Staff` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `People_Users` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `Ph_InEco` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `Ph_InEco_Transactions` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `S_pb_key` MODIFY COLUMN `id` int NOT NULL;--> statement-breakpoint
ALTER TABLE `S_pv_keys` MODIFY COLUMN `id` int NOT NULL;