export const new_Wards = [
  [
    { name: 'رعاية أ', floor: 1, id: 1 },
    { name: 'رعاية ب', floor: 1, id: 2 },
    { name: 'ثاني أ', floor: 2, id: 3 },
    { name: 'ثاني ب', floor: 2, id: 4 },
    { name: 'ثاني ج', floor: 2, id: 5 },
    { name: 'ثاني د', floor: 2, id: 6 },
    { name: 'ثالث أ', floor: 3, id: 7 },
    { name: 'ثالث ب', floor: 3, id: 8 },
    { name: 'ثالث ج', floor: 3, id: 9 },
    { name: 'ثالث د', floor: 3, id: 10 },
    { name: 'رابع أ', floor: 4, id: 11 },
    { name: 'رابع ب', floor: 4, id: 12 },
    { name: 'رابع ج', floor: 4, id: 13 },
    { name: 'رابع د', floor: 4, id: 14 },
  ],
];
export const new_id_doc_type = [
  { name: 'رقم قومي', id: 1 },
  { name: 'جواز سفر', id: 2 },
  { name: 'هوية وطنية', id: 3 },
  { name: 'بطاقة لجوء', id: 4 },
  { name: 'بدون', id: 5 },
];
export const new_Patient_dismissal_reasons = [
  { name: 'تحسن', id: 1 },
  { name: 'حسب الطلب', id: 2 },
  { name: 'تحويل لمستشفى آخر', id: 3 },
  { name: 'وفاة', id: 4 },
  { name: 'هروب', id: 5 },
  { name: 'سوء سلوك', id: 6 },
  { name: 'إلغاء حجز', id: 7 },
  { name: 'نقل إلى مساكن العبور', id: 8 },
];
export const new_Drugs_unit = [
  { name: 'قرص', id: 1 },
  { name: 'كبسول', id: 2 },
  { name: 'أمبول', id: 3 },
  { name: 'فيال', id: 4 },
  { name: 'سرنجة', id: 5 },
  { name: 'كاربولة', id: 6 },
  { name: 'زجاجة', id: 7 },
  { name: 'بخاخة', id: 8 },
  { name: 'قطرة', id: 9 },
  { name: 'لاصقة', id: 10 },
  { name: 'أنبوبة', id: 11 },
  { name: 'كيس', id: 12 },
  { name: 'شريحة', id: 13 },
  { name: 'علبة', id: 14 },
];
export const new_Drugs_category = [
  { name: 'أقراص/كبسولات', id: 1 },
  { name: 'حقن', id: 2 },
  { name: 'مضاد حيوي', id: 3 },
  { name: 'مستنشقات', id: 4 },
  { name: 'محاليل', id: 5 },
  { name: 'مهدئات/مخدرات', id: 6 },
  { name: 'أشربة', id: 7 },
  { name: 'مكملات غذائية', id: 8 },
  { name: 'منوعات', id: 9 },
];
